language: python
python:
  - "3.7"
  - "3.8"
install:
  - python setup.py install
script:
  - python3 -m unittest
matrix:
  include:
    - name: "Python 3.7.4 on macOS 10.14.4"
      os: osx
      osx_image: xcode11.2
      language: shell
      before_install:
        - python3 --version
        - pip3 install --upgrade pip
      install: pip3 install -r requirements-dev.txt
      script: python3 -m unittest
    - name: "Python 3.7.4 on Windows"
      os: windows
      language: shell
      before_install:
        - choco install python --version 3.7.4
        - python --version
        - python -m pip install --upgrade pip
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
